### ISSUE TITLE
希望增加一些可选参数

### ISSUE THREAD

**Issue by hongshaoluobotou** [Guailoudou/openp2p-launcher#3]
1、open2p默认会开启共享限速10mbps，（我和同学联机，但是他那边养了几百只实体，网速不足导致我没能加载进入）。家庭宽带一般限制上传速度50mbps，所以希望把默认速度更改更高（改到25mbps，这足矣应付双人联机下大多数情况了），还希望增加一个可选参数更改最大上传速度，用于应付多人联机。
2、优化重连间隔，比如当稳定游戏超过一段时间后，把重连间隔从2000ms降至0ms，多次尝试无果后才恢复2000ms。防止一些网络波动，比如后台程序突然间启动了多线程下载。

**Comment by Guailoudou** [comment]
1. 默认共享限速我这一直设置的都是100mbps
需要自定义限制可以直接打开bin文件夹内的config.json文件，修改`network.ShareBandwidth`参数的值，然后直接启动openp2p.exe
关于添加启动参数，会考虑（马上开学，未来至少2个月我是没时间的）
2. 程序的sleep2000不是在等待2s后重连，而是2s后重新检查连接状态（状态是连接上的就进行局域网多播，反之则关闭多播）间隔为0会浪费大量cpu算力，openp2p启动之后2个程序是独立运行的

**Comment by hongshaoluobotou** [comment]
嗯~ o(*￣▽￣*)o没有看到json里面那一行，是我疏忽了。
限制网速的是MC，不是你程序的问题，我多开一个MC之后网速便有明显的占用提升了
我找找看有什么办法提高MC这边的网速。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Guailoudou/openp2p-launcher"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月27日(星期二) 下午2:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Guailoudou/openp2p-launcher] 希望增加一些可选参数 (Issue #3)





  
默认共享限速我这一直设置的都是100mbps
 需要自定义限制可以直接打开bin文件夹内的config.json文件，修改network.ShareBandwidth参数的值，然后直接启动openp2p.exe
 关于添加启动参数，会考虑（马上开学，未来至少2个月我是没时间的）
 
程序的sleep2000不是在等待2s后重连，而是2s后重新检查连接状态（状态是连接上的就进行局域网多播，反之则关闭多播）间隔为0会浪费大量cpu算力，openp2p启动之后2个程序是独立运行的

**Comment by hongshaoluobotou** [comment]
、
![屏幕截图 2024-02-27 153056](https://github.com/Guailoudou/openp2p-launcher/assets/133203950/19d17460-89a1-42fc-b2d0-a941a3d4fa1a)

**Comment by hongshaoluobotou** [comment]
![屏幕截图 2024-02-27 153056](https://github.com/Guailoudou/openp2p-launcher/assets/133203950/41a6e651-2b72-4612-96b9-c2acd9e51722)
